pipeline {
    agent any 
    stages {
        stage('release')
        {
           steps{
               withCredentials([steps.usernamePassword(credentialsId: 'GIT', usernameVariable: 'GIT_USERNAME',passwordVariable: 'GIT_PASSWORD')]) {

                    echo '${GIT_USERNAME}'
                    echo '${GIT_PASSWORD}'
                    sh './gradlew releaseVersion'
                }
           }     
        }
    }
}
